name: CICD

on:
  push:
    branches:
      - main
env:
   AWS_REGION: ap-northeast-2
   ECR_ROOT_URL: 084375587480.dkr.ecr.ap-northeast-2.amazonaws.com
   ECR_URL: 084375587480.dkr.ecr.ap-northeast-2.amazonaws.com/cicd-demo:latest
   ECS_CLUSTER_NAME: cicd-demo
   ECS_SERVICE_NAME: cicd-demo-svc
   ECS_TASK_DEFI: cicd-demo-td:2
   
jobs:
  CI:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
        
      - name: JDK 21 설치
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Gradle 명령 실행 권한 부여
        run: chmod +x ./gradlew
        shell: bash

      - name: Gradle로 프로젝트 Build
        run: ls -al && ./gradlew build -x test
      
      - name: jar파일 확인
        run: ls -al && ls -al build && ls -al build/libs

      - name: ECR login
        run: aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{env.ECR_ROOT_URL}}
      - name: Container build
        run: docker build -t ${{ env.ECR_URL }} .
        
      - name: Container Push
        run : docker push ${{ env.ECR_URL }}
  CD:
    name: Deploy
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Deploy to ECS
        run: aws ecs update-service --cluster ${{env.ECS_CLUSTER_NAME}} --service ${{env.ECS_SERVICE_NAME}} --task-definition ${{env.ECS_TASK_DEFI}} --force-new-deployment
